### ISSUE TITLE
onnx_exporter.py

### ISSUE THREAD

**Issue by wafaer** [chenjianqu/Tracking-Solov2-Deepsort#4]
Hello, I put onnx_exporter.py in the SOLO demo and it appears in the 'imported module demo', but the reference 'common' cannot be found. What other files do I need to put in?

**Comment by chenjianqu** [comment]
Sorry，I forgot to put it up. Now in [here](https://github.com/chenjianqu/Solov2-TensorRT-CPP/blob/main/common.py) .
